import header from "./header";
import firstView from "./firstView";
import product from "./product";
import marquee from "./marquee";
import toggle_marquee from "./toggle_marquee";
import review from "./review";
import media from "./media";
import faq from "./faq";
import banner from "./banner";
